#%RAML 0.8
title: Orders API
version: "1.0.0"
baseUri: "http://qas.qmetry.com/struts2-rest-showcase-2.3.16.3"
/employee.json: 
    displayName: Get all employee data
    get: 
        displayName: Get all employee data
    