#%RAML 0.8
title: Hello API
version: "1.0.0"
baseUri: "http://localhost:8080/Server_hello_jersey/rest-points/show-on-screen"
/hello/{msg}.text: 
    displayName: Display Text
    get: 
        displayName: Display Text
    